add luciano do valle
IgorHalfeld/pr-maneiro pull request #114
Opened 2024-10-22 14:43 UTC by conradolucas

2024-10-23 17:31 UTC, IgorHalfeld commented on scripts/app.js
> +      .sort(function (a, b) {
Dá um revert aqui pro arquivo original

2024-10-23 17:32 UTC, IgorHalfeld requested changes
Pequenas coisas só

2024-10-30 22:26 UTC, conradolucas commented on scripts/app.js
> +      .sort(function (a, b) {
Mano, alterei porque tá falhando lint no pre-commit

2024-10-31 12:10 UTC, IgorHalfeld commented on scripts/app.js
> +      .sort(function (a, b) {
é que tu não mexeu aí né? não tem porque ter alteração nesse arquivo

2024-11-11 21:14 UTC, IgorHalfeld commented
@conradolucas updates bro?

2024-11-29 18:43 UTC, IgorHalfeld commented
Fechando, qualquer coisa abre outro irmão!

2024-11-29 18:43 UTC, closed without merging