Fix: Manter tweet digitado ao trocar de template
IgorHalfeld/pr-maneiro pull request #85
Opened 2020-10-30 18:04 UTC by omarkdev

Quando se tem um tweet já digitado, ao trocar de template, o novo template não vem com o tweet digitado, porém a mensagem fica digitado no campo. Este PR tem como objetivo corrigir isso: ao ter um tweet já digitado, quando trocar de template, o novo template já vem com o que está digitado.

2020-10-30 22:41 UTC, IgorHalfeld requested changes
Achei um bug xD

![gif](https://user-images.githubusercontent.com/9022134/97762597-d3e99400-1ae7-11eb-8f49-95d137e55714.gif)

2020-10-30 22:45 UTC, omarkdev commented
Vou corrigir

Em sex, 30 de out de 2020 19:41, Igor Luiz Halfeld <notifications@github.com>
escreveu:

> *@IgorHalfeld* requested changes on this pull request.
>
> Achei um bug xD
>
> [image: gif]
> <https://user-images.githubusercontent.com/9022134/97762597-d3e99400-1ae7-11eb-8f49-95d137e55714.gif>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/IgorHalfeld/pr-maneiro/pull/85#pullrequestreview-521072523>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADR6RMJXAOBZAR7I3OB6ELDSNM6I7ANCNFSM4TFITKFA>
> .
>

2020-10-30 22:54 UTC, omarkdev commented
@IgorHalfeld corrigido! A solução foi no `handleTweetMessageChange` usar o parametro `msg` para definir o `search` ao invés do `tweet.msg` (o que para mim faz mais sentido também, pois acredito que o `search` deva representar o que está digitado na caixa e não o valor padrão de algo)

2020-11-03 04:38 UTC, IgorHalfeld approved these changes

2020-11-03 04:38 UTC, IgorHalfeld commented
![image](https://user-images.githubusercontent.com/9022134/97950321-41f6bb00-1d75-11eb-9716-0b9549e99ded.png)

2020-11-03 04:38 UTC, merged